// src/owner/backup/types/error-codes.ts

/**
 * أكواد الأخطاء القياسية لنظام النسخ الاحتياطي (BKP-001)
 */
export const BackupErrorCodes = {
  // ── Backup ──
  BACKUP_ALREADY_RUNNING: 'BACKUP_ALREADY_RUNNING',
  BACKUP_NOT_FOUND: 'BACKUP_NOT_FOUND',
  BACKUP_PACKAGE_CORRUPTED: 'BACKUP_PACKAGE_CORRUPTED',
  BACKUP_CHECKSUM_MISMATCH: 'BACKUP_CHECKSUM_MISMATCH',
  BACKUP_IS_PINNED: 'BACKUP_IS_PINNED',
  BACKUP_IN_USE: 'BACKUP_IN_USE',
  BACKUP_COMPONENT_NOT_AVAILABLE: 'BACKUP_COMPONENT_NOT_AVAILABLE',

  // ── Restore ──
  RESTORE_ALREADY_RUNNING: 'RESTORE_ALREADY_RUNNING',
  SAFETY_BACKUP_FAILED: 'SAFETY_BACKUP_FAILED',
  INVALID_RESTORE_REQUEST: 'INVALID_RESTORE_REQUEST',
  RESTORE_ROLLBACK_FAILED: 'RESTORE_ROLLBACK_FAILED',
  INVALID_MANIFEST: 'INVALID_MANIFEST',
  MANIFEST_VERSION_UNSUPPORTED: 'MANIFEST_VERSION_UNSUPPORTED',
  CHECKSUM_FILE_MISSING: 'CHECKSUM_FILE_MISSING',
  BACKUP_FILE_NOT_FOUND: 'BACKUP_FILE_NOT_FOUND',

  // ── Infrastructure ──
  INSUFFICIENT_DISK_SPACE: 'INSUFFICIENT_DISK_SPACE',
  STORAGE_PROVIDER_ERROR: 'STORAGE_PROVIDER_ERROR',
  TOOL_NOT_AVAILABLE: 'TOOL_NOT_AVAILABLE',
  DATABASE_CONNECTION_FAILED: 'DATABASE_CONNECTION_FAILED',
  WRITE_PERMISSION_DENIED: 'WRITE_PERMISSION_DENIED',
} as const;

export type BackupErrorCode =
  (typeof BackupErrorCodes)[keyof typeof BackupErrorCodes];
