// src/public/student-registration/registration.constants.ts

/**
 * أخطاء التسجيل الذاتي
 */
export const REGISTRATION_ERRORS = {
  TOKEN_INVALID: 'REGISTRATION_TOKEN_INVALID',
  TOKEN_EXPIRED: 'REGISTRATION_TOKEN_EXPIRED',
  PHONE_ALREADY_REGISTERED: 'PHONE_ALREADY_REGISTERED',
  MAFHOOM_SCHOOL_NOT_FOUND: 'MAFHOOM_SCHOOL_NOT_FOUND',
  NO_CURRENT_YEAR: 'NO_CURRENT_YEAR',
  GRADE_NOT_FOUND: 'GRADE_NOT_FOUND',
  SECTION_NOT_FOUND: 'SECTION_NOT_FOUND',
  PROVINCE_NOT_FOUND: 'PROVINCE_NOT_FOUND',
  DISTRICT_NOT_FOUND: 'DISTRICT_NOT_FOUND',
  ROUTING_NOT_FOUND: 'ROUTING_NOT_FOUND',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  SESSION_CREATION_FAILED: 'SESSION_CREATION_FAILED',
};

/**
 * إعدادات التسجيل — مدرسة مفهوم
 */
export const REGISTRATION_CONFIG = {
  /** رمز مدرسة مفهوم */
  mafhoomSchoolCode: parseInt(process.env.MAFHOOM_SCHOOL_CODE || '0', 10),
};
