// src/school/auth/constants.ts

/**
 * أخطاء المصادقة الخاصة بالمدارس
 */
export const SCHOOL_AUTH_ERRORS = {
  SCHOOL_NOT_FOUND: 'SCHOOL_NOT_FOUND',
  SCHOOL_INACTIVE: 'SCHOOL_INACTIVE',
  SCHOOL_CODE_MISMATCH: 'SCHOOL_CODE_MISMATCH',
  SCHOOL_SCOPE_MISMATCH: 'SCHOOL_SCOPE_MISMATCH',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_INACTIVE: 'USER_INACTIVE',
  USER_NOT_IN_SCHOOL: 'USER_NOT_IN_SCHOOL',
  USER_TYPE_NOT_ALLOWED: 'USER_TYPE_NOT_ALLOWED',

  DEVICE_FINGERPRINT_REQUIRED: 'DEVICE_FINGERPRINT_REQUIRED',
  DEVICE_NOT_FOUND: 'DEVICE_NOT_FOUND',
  DEVICE_INACTIVE: 'DEVICE_INACTIVE',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',

  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SESSION_REVOKED: 'SESSION_REVOKED',
  INVALID_SESSION: 'INVALID_SESSION',
  NOT_YOUR_SESSION: 'NOT_YOUR_SESSION',

  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',

  RATE_LIMITED: 'RATE_LIMITED',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
};

/**
 * إعدادات JWT للمدارس
 */
export const SCHOOL_AUTH_JWT = {
  accessTokenTtlSec: 60 * 15,          // 15m
  refreshTokenTtlSec: 60 * 60 * 24 * 30, // 30d
  issuer: 'asas-backend',
  audience: 'asas-school-app',
};

/**
 * رؤوس HTTP المطلوبة
 */
export const SCHOOL_AUTH_HEADERS = {
  schoolUuid: 'x-school-uuid',
};
